### ISSUE TITLE
File not recognized/not exporting properly

### ISSUE THREAD

**Issue by MHFDoge** [miniaturepets/miniaturepets#115]
I'm having issues with creating a custom basic "MiniMe" style pet, and after one attempt which was closer to "custom" than the second one, it would not register the file as a valid pet. On the second attempt, I took the contents of a working "MiniMe" pet file, made some basic changes, and then converted it back to the proper extension(.mpet). On reuploading the new file to the FTP server, the server continued to throw the error. I have attached the working file and the erroring file. Any idea as to why it's not working?
[Erroring_mpet_inside.zip](https://github.com/miniaturepets/miniaturepets/files/3474513/Erroring_mpet_inside.zip)
[Working mpet inside.zip](https://github.com/miniaturepets/miniaturepets/files/3474518/Working.mpet.inside.zip)

**Comment by crispyklown81** [comment]
A couple things I noticed when I opened the archive of the error pet is that all the files were in a numbered folder, normally when i open the archive all the files are right there. Also the skull was done wrong, instead of doing owner: "MHF_Doge", do SkullURL: placeskullurlhere with no quotations. Attached is a fixed copy of MHF_Doge mini. Also, not sure if this really matters but generally when setting the permission is best to do lowercase instead of caps, thats just what i've always known as a rule of thumb for permissions, again not sure that really matters in this case, Hope this helps you for future pets.
[MHF_Doge.zip](https://github.com/miniaturepets/miniaturepets/files/3477335/MHF_Doge.zip)
I hope I attached the fixed zip file correctly XD

**Comment by MHFDoge** [comment]
Oh, Yeah I couldn't find the tool to get the skull url. the testserver was offline/refusing connection and I could not find a link to the plugin to set it up elsewhere.

**Comment by MHFDoge** [comment]
Thank you.

**Comment by crispyklown81** [comment]
Your welcome

**Comment by MHFDoge** [comment]
What tool did you use to get the skull url's?

**Comment by MHFDoge** [comment]
Ive tried the GET from mojang sessionservers, the tools provided on other websites, nothing worked.

**Comment by MHFDoge** [comment]
That numbered folder must have created itself when I converted the file.

**Comment by crispyklown81** [comment]
I cant get on my pc at the moment but as soon as i can ill get the links, theres 2 different ones, one to get the head code, and one to decode to get the url

**Comment by MHFDoge** [comment]
Ah, I just realized I never decoded the output,
I just decoded it and it showed the url.
Thank you for your help

**Comment by crispyklown81** [comment]
Your welcome
