### ISSUE TITLE
The plugin does not work on my server

### ISSUE THREAD

**Issue by GTBelo** [miniaturepets/miniaturepets#138]
*Short Description:* 

*Long Description:* 

Does this plugin have any dependencies? I tested 7 versions of it on my server and none worked. can you help me?

*Instructions for Re-Producing The Bug:* The plugin does not work on my serverr.

My Worldguard version: 5.7.3

Mt Spigot Version: 1.8.3

*Dump File Link:*

http://prntscr.com/qom6s5

http://prntscr.com/qom74n

**Comment by GTBelo** [comment]
I'm using Petblock-Bukkit

**Comment by Amokinio** [comment]
Hi, I don't know what is Petblock-Bukkit, is it some sort of a Bukkit forge? MPets only runs on Spigot 1.8.8 or higher. This plugin has no dependencies, but there are many plugins that may interfere with MPets. Please write down the error you receive when trying to start the server, because all of the errors which are the most important part of the logs are hidden due to rate limiting in your server.


Thanks,
Amokinio.

**Comment by Amokinio** [comment]
This is closed due to no answer for over 48 hours. Please reopen if you are still facing this issue.
